"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)

# Set the project base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# --- NOW USE THE VARIABLES ---
SECRET_KEY = env('SECRET_KEY')

CHAPA_URL = env('CHAPA_URL')  # Use the environment variable for Chapa URL

# Chapa Key
CHAPA_SECRET_KEY = env('CHAPA_SECRET_KEY')

print("CHAPA_URL:", CHAPA_URL)
print("DEBUG: CHAPA KEY EXISTS:", bool(CHAPA_SECRET_KEY))

if CHAPA_SECRET_KEY:
    print("DEBUG: CHAPA KEY PREFIX:", CHAPA_SECRET_KEY[:15])


BASE_URL_DOMAIN = env('BASE_URL_DOMAIN')

print("DEBUG: BASE_URL_DOMAIN:", BASE_URL_DOMAIN)

DEBUG = env('DEBUG')
# Handle Wildcard Subdomains safely

# 1. Allow the pinggy domain to hit your server
# ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '.localhost'])
# Add the specific pinggy domain from your terminal output here
#ALLOWED_HOSTS.append('https://jpdpq-196-190-157-91.run.pinggy-free.link') 

ALLOWED_HOSTS = ['*']

# 2. CRITICAL for Webhooks: Allow CSRF for the external domain
CSRF_TRUSTED_ORIGINS = [
    'https://gavdv-196-190-157-91.run.pinggy-free.link',
    'https://*.pinggy.link',
    'https://*.pinggy-free.link',
    'http://localhost:5173',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ... default apps ...
    'rest_framework',
    'corsheaders',
    'drf_spectacular',  

    # Custom apps
    'users',
    'core',
    'exams',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.TenantMiddleware',  # custom middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow any subdomain of localhost on the React port (5173)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://.*\.localhost:5173$",
    r"^http://localhost:5173$",
]


CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration

print(f"DEBUG {env('DEBUG')}")
# sq_name = env('SQLITE_DB_NAME')

if env('DEBUG'):
    print(f"DEBUG  is TRUE")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

else: 
    print(f"DEBUG  is FALSE")
    DATABASES = {
        'default': env.db(), # This automatically parses DATABASE_URL
    }









# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 3. (Optional) If you have a global 'static/' folder for your own CSS/Images
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# The URL the browser uses
MEDIA_URL = '/media/'

# The actual path
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Lock everything down by default
        'core.permissions.IsWorkspaceMember',# This makes every single new API view tenant-locked by default!
    ],
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}