# Generated by Django 6.0.5 on 2026-05-31 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="examresponse",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="exams.examattempt",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="competency_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.competencyarea",
            ),
        ),
        migrations.AddField(
            model_name="examresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.question"
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="exams.question",
            ),
        ),
        migrations.AddField(
            model_name="examresponse",
            name="selected_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.questionoption"
            ),
        ),
    ]
