# Generated by Django 6.0.5 on 2026-06-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examattempt_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='university',
        ),
    ]
