# Generated by Django 6.0.5 on 2026-06-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_department_category'),
        ('exams', '0004_remove_examattempt_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.university'),
            preserve_default=False,
        ),
    ]
