# Generated by Django 6.0.5 on 2026-08-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examattempt_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='competency_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.competencyarea'),
        ),
    ]
