# Generated by Django 6.0.5 on 2026-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_examattempt_competency_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
