# Generated by Django 6.0.5 on 2026-09-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencyarea',
            name='name',
            field=models.CharField(default='Mock Exit Exam', max_length=255),
        ),
    ]
