# Generated by Django 6.0.5 on 2026-05-31 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchercode",
            name="redeemed_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voucher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vouchercode",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.university"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["university", "name"], name="core_depart_univers_6a978c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vouchercode",
            index=models.Index(
                fields=["university", "code"], name="core_vouche_univers_474443_idx"
            ),
        ),
    ]
