# Generated by Django 6.0.5 on 2026-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='voucher_balance',
            field=models.PositiveIntegerField(default=0, help_text='Number of student seats available to generate vouchers for.'),
        ),
    ]
