# Generated by Django 6.0.5 on 2026-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_universitybooksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('MGMT', 'Management'), ('MMGMT', 'Marketing'), ('ACC', 'Accounting and Finance')], db_index=True, max_length=50),
        ),
    ]
