# Generated by Django 6.0.5 on 2026-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='primary_color',
            field=models.CharField(default='#4f46e5', help_text="Hex code for the university's primary brand color (e.g. #FF0000)", max_length=7),
        ),
    ]
