# Generated by Django 6.0.5 on 2026-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_university_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university-logos/'),
        ),
    ]
