# Generated by Django 6.0.5 on 2026-09-09 13:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercode',
            name='code',
            field=models.CharField(default=core.models.generate_voucher_code, max_length=50),
        ),
    ]
